apiVersion: v1
kind: ServiceAccount
metadata:
  name: nest-ms-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-ms-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-ms-client
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'nest-ms-mail:5000'
      labels:
        app: nest-ms-client
    spec:
      containers:
        - name: client
          image: wyfy/nest-ms-client:2.0
          ports:
            - containerPort: 5001
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nest-ms-client
spec:
  selector:
    app: nest-ms-client
  ports:
    - port: 80
      targetPort: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nest-ms-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-ms-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-ms-user
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: nest-ms-user
    spec:
      containers:
        - name: user
          image: wyfy/nest-ms-user
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nest-ms-user
spec:
  selector:
    app: nest-ms-user
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nest-ms-mail
---
apiVersion: v1
kind: Service
metadata:
  name: nest-ms-mail
spec:
  selector:
    app: nest-ms-mail
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-ms-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-ms-mail
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'nest-ms-user:3000'
      labels:
        app: nest-ms-mail
    spec:
      containers:
        - name: mail
          image: wyfy/nest-ms-mail
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
